version: "3.7"

services:
  db:
    image: mysql
    container_name: movierentalapi_db
    restart: always
    volumes:
      - movierentalapi_db:/data/db
    ports:
      - ${DB_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}

volumes:
  movierentalapi_db:
    name: movierentalapi_db