CREATE DATABASE MOVIERENTALDB;

USE MOVIERENTALDB;

CREATE TABLE USERS (
    id INT(6) UNSIGNED AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(50) NOT NULL UNIQUE, 
    password VARCHAR(100) NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE MOVIES (
    id INT(6) UNSIGNED AUTO_INCREMENT,
    title VARCHAR(100) NOT NULL UNIQUE,
    director VARCHAR (100) NOT NULL,
    copy_amount INT(2) UNSIGNED NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE RENTALS (
    id INT(6) UNSIGNED AUTO_INCREMENT,
    `user_id` INT(6) UNSIGNED NOT NULL,
    `movie_id` INT(6) UNSIGNED NOT NULL,
    PRIMARY KEY (id),
    
	CONSTRAINT `fk_id_users`
		FOREIGN KEY (`user_id`) 
        REFERENCES USERS(id) 
        ON DELETE CASCADE 
        ON UPDATE CASCADE,
	
    CONSTRAINT `fk_id_movies`
		FOREIGN KEY (`movie_id`) 
        REFERENCES MOVIES(id) 
        ON DELETE CASCADE 
        ON UPDATE CASCADE
);